Update patch set 1
Patch Set 1: Code-Review+1

From LA.QSSI.11.0.r1-11100.01-qssi.0.
Needed to fix crash when calling on newer radio blobs:

E/AndroidRuntime(2444): java.lang.NoSuchMethodError: No static method isVideoCrsSupported(ILandroid/content/Context;)Z in class Lorg/codeaurora/ims/utils/QtiImsExtUtils; or its super classes (declaration of 'org.codeaurora.ims.utils.QtiImsExtUtils' appears in /product/framework/ims-ext-common.jar)

Patch-set: 1
Reviewer: Gerrit User 211 <211@66da7299-18b4-411a-8fa2-12a880778196>
Label: Code-Review=+1